### ISSUE TITLE
Todo list for v0.30

### ISSUE THREAD

**Issue by innesbre** [BaderLab/scClustViz#4]
- [x] Log colour scale breaks when zeroes exist (metadata overlays)
- [x] Remove log-axis option when that axis is a boxplot (metadata scatterplot)
- [x] Log axis with boxplots breaks when zeroes exist
- [x] Label angle in MA plot shifted closer to horizontal
- [x] Colour bar of cluster colours for dotplot rows
- [x] selDE metadata legend goes outside margins
- [x] Default scatterplot inputs should be first and second entries of metadata
- [x] **Legend needed for dotplot!**
